name: Build and Push vscode-web Image

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 7 * * *"

jobs:
  vscode-web-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "NOW=$(date +'%d%m%Y')" >> $GITHUB_ENV
      - name: Build and push vscode-web
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            bjornjorgensen/vscode-web:${{ env.NOW }}
            bjornjorgensen/vscode-web:latest